version: '3.1'
volumes:
    fsc-data:
services:
    fsc-postgres:
        image: postgres
        ports:
            - 5433:5432
        volumes:
            - ./data/postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: fsc_develop
            POSTGRES_PASSWORD: bosZRKz0JyABAoJXLhWwNPPUQq9FTnC7sh7DIoZo
            POSTGRES_DB: fsc_develop
        restart: always

    base_fsc_endpoint:
        image: postgrest/postgrest
        ports:
          - "8011:3000"
        environment:
          PGRST_DB_URI: postgres://fsc_develop:bosZRKz0JyABAoJXLhWwNPPUQq9FTnC7sh7DIoZo@localhost:5433/fsc_develop
          PGRST_DB_SCHEMA: BASE
          PGRST_DB_ANON_ROLE: postgres
        restart: always