version: '3.1'
volumes:
    postgres-data:
services:
    qmx_api_endpoint:
        image: postgrest/postgrest
        ports:
          - "7011:3000"
        environment:
          PGRST_DB_URI: postgres://mjl_develop:peo6bzwyawkl7c7T83yfFYSzddOl7qmr2Lk=@postgres.mjl.svc.fiisoft.net:5432/mjl_develop
          PGRST_DB_SCHEMA: QMX
          PGRST_DB_ANON_ROLE: mjl_develop
        restart: always

    reg_api_endpoint:
        image: postgrest/postgrest
        ports:
          - "7012:3000"
        environment:
          PGRST_DB_URI: postgres://mjl_develop:peo6bzwyawkl7c7T83yfFYSzddOl7qmr2Lk=@postgres.mjl.svc.fiisoft.net:5432/mjl_develop
          PGRST_DB_SCHEMA: REG
          PGRST_DB_ANON_ROLE: mjl_develop
        restart: always

    base_api_endpoint:
        image: postgrest/postgrest
        ports:
          - "7013:3000"
        environment:
          PGRST_DB_URI: postgres://mjl_develop:peo6bzwyawkl7c7T83yfFYSzddOl7qmr2Lk=@postgres.mjl.svc.fiisoft.net:5432/mjl_develop
          PGRST_DB_SCHEMA: BASE
          PGRST_DB_ANON_ROLE: mjl_develop
        restart: always

    cmp_api_endpoint:
        image: postgrest/postgrest
        ports:
          - "7014:3000"
        environment:
          PGRST_DB_URI: postgres://mjl_develop:peo6bzwyawkl7c7T83yfFYSzddOl7qmr2Lk=@postgres.mjl.svc.fiisoft.net:5432/mjl_develop
          PGRST_DB_SCHEMA: CMP
          PGRST_DB_ANON_ROLE: mjl_develop
        restart: always

    jmx_api_endpoint:
        image: postgrest/postgrest
        ports:
          - "7015:3000"
        environment:
          PGRST_DB_URI: postgres://mjl_develop:peo6bzwyawkl7c7T83yfFYSzddOl7qmr2Lk=@postgres.mjl.svc.fiisoft.net:5432/mjl_develop
          PGRST_DB_SCHEMA: JMX
          PGRST_DB_ANON_ROLE: mjl_develop
        restart: always

    trn_api_endpoint:
        image: postgrest/postgrest
        ports:
          - "7016:3000"
        environment:
          PGRST_DB_URI: postgres://mjl_develop:peo6bzwyawkl7c7T83yfFYSzddOl7qmr2Lk=@postgres.mjl.svc.fiisoft.net:5432/mjl_develop
          PGRST_DB_SCHEMA: TRN
          PGRST_DB_ANON_ROLE: mjl_develop
        restart: always

    cqrs_api_endpoint:
        image: postgrest/postgrest
        ports:
          - "7017:3000"
        environment:
          PGRST_DB_URI: postgres://mjl_develop:peo6bzwyawkl7c7T83yfFYSzddOl7qmr2Lk=@postgres.mjl.svc.fiisoft.net:5432/mjl_develop
          PGRST_DB_SCHEMA: CQRS
          PGRST_DB_ANON_ROLE: mjl_develop
        restart: always

    db:
        image: postgres
        ports:
            - 5432:5432
        volumes:
            - ./data/postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: fitznguyen
            POSTGRES_PASSWORD: fitznguyen
            POSTGRES_DB: mjl_develop
        restart: always

    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - ./data/db:/data/db
        ports:
            - 27017:27017
        command: mongod --logpath=/dev/null # --quiet
        restart: always