version: '3.1'
volumes:
    postgres-data:
services:
    server:
        image: postgrest/postgrest
        ports:
          - "3000:3000"
        # links:
        #   - db:db
        environment:
          PGRST_DB_URI: postgres://mjl_develop:peo6bzwyawkl7c7T83yfFYSzddOl7qmr2Lk=@postgres.mjl.svc.fiisoft.net:5432/mjl_develop
          PGRST_DB_SCHEMA: REG
          PGRST_DB_ANON_ROLE: postgres #In production this role should not be the same as the one used for the connection
        # depends_on:
        #   - db
        # restart: always
    server:
        image: postgrest/postgrest
        ports:
          - "3001:3000"
        # links:
        #   - db:db
        environment:
          PGRST_DB_URI: postgres://mjl_develop:peo6bzwyawkl7c7T83yfFYSzddOl7qmr2Lk=@postgres.mjl.svc.fiisoft.net:5432/mjl_develop
          PGRST_DB_SCHEMA: REG
          PGRST_DB_ANON_ROLE: postgres #In production this role should not be the same as the one used for the connection
        # depends_on:
        #   - db
        # restart: always
    server2:
        image: postgrest/postgrest
        ports:
          - "3002:3000"
        # links:
        #   - db:db
        environment:
          PGRST_DB_URI: postgres://mjl_develop:peo6bzwyawkl7c7T83yfFYSzddOl7qmr2Lk=@postgres.mjl.svc.fiisoft.net:5432/mjl_develop
          PGRST_DB_SCHEMA: BASE
          PGRST_DB_ANON_ROLE: postgres #In production this role should not be the same as the one used for the connection
        # depends_on:
        #   - db
        # restart: always
    server2:
        image: postgrest/postgrest
        ports:
          - "4000:3000"
        # links:
        #   - db:db
        environment:
          PGRST_DB_URI: postgres://mjl_develop:peo6bzwyawkl7c7T83yfFYSzddOl7qmr2Lk=@postgres.mjl.svc.fiisoft.net:5432/mjl_develop
          PGRST_DB_SCHEMA: BASE
          PGRST_DB_ANON_ROLE: postgres #In production this role should not be the same as the one used for the connection
        # depends_on:
        #   - db
        # restart: always
    db:
        image: postgres
        ports:
            - 5432:5432

        environment:
            POSTGRES_USER: fitznguyen
            POSTGRES_PASSWORD: fitznguyen
            POSTGRES_DB: fitznguyen
        # restart: always
    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - ./data/db:/data/db
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet
        restart: always