version: '3.1'
volumes:
    postgres-data:
services:
  db:
    image: postgres
    restart: always
    ports:
        - 5432:5432
    volumes:
        - postgres-data:/var/lib/postgresql/data
        - /Users/fitznguyen/workspaces/test/postgres:/app/dvdrental

    environment:
        POSTGRES_USER: fitznguyen
        POSTGRES_PASSWORD: fitznguyen
        POSTGRES_DB: fitznguyen
